<?php

namespace Pizza\shopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SoldProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldProductsRepository extends EntityRepository
{
}
