<?php

namespace Pizza\shopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TelListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelListRepository extends EntityRepository
{
}
