pizzalogin:
    resource: "@PizzaloginBundle/Controller/"
    type:     annotation
    prefix:   /

pizzashop:
    resource: "@PizzashopBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path:     /logout

acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

random:
    path:     /random/{limit}
    defaults: { _controller: AcmeDemoBundle:Random:index }
