security:
    encoders:
        Pizza\shopBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
       administrators:
           entity: { class: PizzashopBundle:User, property: username }

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login: 
                login_path: /login
                check_path: /login_check
                default_target_path: /cart

            logout:
                path:   /logout
                target: /cart


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
